name: ci

on: [push]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@lamalex"
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:types
      - run: pnpm build
      - name: nightly release
        run: pnpm changelogen --canary nightly --publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
